[package]
name = "l4r5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { git = "https://github.com/OsirisRTOS/cortex-m.git", version = "0.7.4" }

[lib]
name = "l4r5"
path = "lib.rs"
